Repository tokenami/tokenami, pull requests merged in 2024-12, with the labels that each got.

#394 [ds] add `color-space` property for configuring `srgb`, `oklch`, or `oklab`
  .github/workflows/release-discord.yaml
  examples/design-system/.tokenami/tokenami.env.d.ts
  examples/remix/.tokenami/tokenami.env.d.ts
  packages/ds/README.md
  packages/ds/src/index.ts
Labels: major, skip-release

#397 [ds] fix `webkit-search-decoration` pseudo-element selector
  packages/ds/src/index.ts
Labels: patch, skip-release

#395 [ds] add `mix-{}-color` and `mix-{}-percent` properties for color opacity, tint, and shade
  examples/design-system/.tokenami/tokenami.env.d.ts
  examples/remix/.tokenami/tokenami.env.d.ts
  packages/ds/README.md
  packages/ds/src/index.ts
Labels: minor, skip-release

#396 [ds] replace alpha tokens with number type
  packages/ds/src/index.ts
Labels: major
